#!/usr/bin/env bash
#script that configures an Ubuntu server with the below requirements.

if [ "$EUID" -ne 0 ]; then
    echo "Please run as root"
    exit
fi

sed -i '/localhost/c\127.0.0.2 localhost' /etc/hosts
sed -i '/facebook.com/c\8.8.8.8 facebook.com' /etc/hosts

echo "Changes applied successfully. Please check the /etc/hosts file."
